// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/goodbye/[name].tsx";
import * as $4 from "./routes/hello/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/post/[color]/[id].tsx";
import * as $7 from "./routes/posts.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/ListItem.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/goodbye/[name].tsx": $3,
    "./routes/hello/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/post/[color]/[id].tsx": $6,
    "./routes/posts.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/ListItem.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
