// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/goodbye/[name].tsx";
import * as $2 from "./routes/hello/[name].tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/post/[color]/[id].tsx";
import * as $5 from "./routes/posts.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/ListItem.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/goodbye/[name].tsx": $1,
    "./routes/hello/[name].tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/post/[color]/[id].tsx": $4,
    "./routes/posts.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/ListItem.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
